name: Feature request
description: Suggest an idea or support for another device
labels: enhancement
body:
  - type: markdown
    attributes:
      value: Please search the [existing issues](https://github.com/nyffchanium/argoclima-integration/issues) first.
  - type: textarea
    attributes:
      label: Problem or use case
      description: What would you like to do that isn't possible today?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed solution
  - type: input
    attributes:
      label: Device model
      description: If this is about a specific Argo device, which one?
