set_time:
  fields:
    device:
      required: true
      selector:
        device:
          integration: argoclima
    time:
      required: false
      selector:
        time:
    weekday:
      required: false
      selector:
        select:
          translation_key: weekday
          options:
            - monday
            - tuesday
            - wednesday
            - thursday
            - friday
            - saturday
            - sunday
