name: Release

on:
  release:
    types:
      - published

permissions: {}

jobs:
  release:
    name: Attach integration archive
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7

      - name: Set version from tag
        env:
          TAG: ${{ github.event.release.tag_name }}
        run: |
          yq -i -o json ".version=\"${TAG#v}\"" custom_components/argoclima/manifest.json

      - name: Create archive
        working-directory: custom_components/argoclima
        run: zip -r "$GITHUB_WORKSPACE/argoclima_integration.zip" .

      - uses: softprops/action-gh-release@v3
        with:
          files: argoclima_integration.zip
